Repository GPII/gpii-app, pull requests merged in 2020-05, with the labels that each got.

#138 GPII-3705: Reduced the chances of the tray button not showing.
  tests/TrayButtonTests.js
  trayButton/tray-button.c
Labels: 1.3.x

#175 GPII-4286: Unnecessary redirect notices (change urls) v2
  messageBundles/gpii-app-qss-settings_en.json
Labels: 1.3.x, Needs Work

#164 GPII-4227: Replaced MySavedSettingsBtn onClick invoker to be a listener
  src/renderer/qssWidget/js/qssMySavedSettingsWidget.js
Labels: 1.3.x

#83 GPII-1908 Initial Prototype of Capture Tool
  package.json
  src/main/app.js
  src/main/dialogs/captureToolDialog.js
  src/main/menu.js
  src/renderer/captureTool/Morphic_icon_animated_128.gif
  src/renderer/captureTool/at_home.png
  src/renderer/captureTool/at_work.png
  src/renderer/captureTool/css/captureDialogue.css
  src/renderer/captureTool/html/1_ready_to_capture.handlebars
  src/renderer/captureTool/html/1_sign_in.handlebars
  src/renderer/captureTool/html/3_capturing_settings.handlebars
  src/renderer/captureTool/html/3_what_to_keep.handlebars
  src/renderer/captureTool/html/4_confirm_update_prefsset.handlebars
  src/renderer/captureTool/html/4_save_choose_prefsset.handlebars
  src/renderer/captureTool/html/4_save_name.handlebars
  src/renderer/captureTool/html/5_confirmation.handlebars
  src/renderer/captureTool/html/5_error_confirmation.handlebars
  src/renderer/captureTool/html/footer_location_partial.handlebars
  src/renderer/captureTool/html/page_header_partial.handlebars
  src/renderer/captureTool/index.html
  src/renderer/captureTool/js/capture.js
  src/renderer/captureTool/js/common-event-bindings.js
  src/renderer/captureTool/js/index.js
  src/renderer/captureTool/save_new_set.png
  src/renderer/captureTool/u128.png
  tests/IntegrationTestDefs.js
Labels: Morphic 1.3.5, Priority
